#!/usr/bin/env bash

# Validate production configuration and start the current Docker Compose stack.
# Database provisioning and secret management are intentionally kept outside
# this repository; do not put credentials in this script or in Git.

set -Eeuo pipefail

readonly APP_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly COMPOSE_FILE="${APP_ROOT}/compose.yaml"
readonly ENV_FILES=(
  "${APP_ROOT}/user_ecommere/backend/.env"
  "${APP_ROOT}/admin_ecommere/backend/.env"
)
readonly REQUIRED_VARS=(
  DATABASE_URL
  JWT_ACCESS_SECRET
  JWT_REFRESH_SECRET
  CORS_ORIGIN
  CLOUDINARY_CLOUD_NAME
  CLOUDINARY_API_KEY
  CLOUDINARY_API_SECRET
)

fail() {
  printf 'Deployment validation failed: %s\n' "$1" >&2
  exit 1
}

cd "$APP_ROOT"

[[ -f "$COMPOSE_FILE" ]] || fail "compose.yaml was not found"
command -v docker >/dev/null 2>&1 || fail "Docker is required"
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required"

for env_file in "${ENV_FILES[@]}"; do
  [[ -f "$env_file" ]] || fail "missing environment file: ${env_file#"$APP_ROOT/"}"

  for variable in "${REQUIRED_VARS[@]}"; do
    grep -Eq "^${variable}=.+$" "$env_file" || \
      fail "${variable} is missing from ${env_file#"$APP_ROOT/"}"
  done

  if grep -Eiq 'replace[-_ ]?with|change[-_ ]?in[-_ ]?production|example[-_ ]?password|demo[-_ ]?password' "$env_file"; then
    fail "placeholder or demo credentials found in ${env_file#"$APP_ROOT/"}"
  fi
done

docker compose -f "$COMPOSE_FILE" config --quiet
docker compose -f "$COMPOSE_FILE" build
docker compose -f "$COMPOSE_FILE" run --rm --no-deps backend npx prisma db push --skip-generate
docker compose -f "$COMPOSE_FILE" up -d
docker compose -f "$COMPOSE_FILE" ps

printf '%s\n' 'Deployment completed. Secrets were read from the environment files and were not generated by this script.'
